version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.dockerfile  # Update this to the correct file name
    ports:
      - "89:80"
    depends_on:
      - app
    environment:
      DB_HOST: db 

    networks:
      - laravel

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: laravel_devops
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
