version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: laravel_devops
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    container_name: server
    build:
      context: .
      dockerfile: nginx/nginx.dockerfile  # Update this to the correct file name
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
